apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsexercise-demo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      devopsexercise: web
  template:
    metadata:
      labels:
        devopsexercise: web
    spec:
      containers:
      - name: devops-exercise
        image: ghcr.io/bcruik/devops-exercise/devops-exercise:17
        env:
        - name: DB_URL
          value: "postgresql://devops:TZzXTzTZzXTz@rds.cqz7muyupn1s.ap-southeast-2.rds.amazonaws.com:5432/thedb"
        - name: PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: devopsexercise-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    devopsexercise: web
  ports:
  - port: 3000
    targetPort: 80
    nodePort: 30001