on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        yarn install
        yarn build
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist